name: Compile Lua Scripts

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Lua Scripts
        run: |
          # Installer LuaJIT (Linux)
          sudo apt-get update -qq
          sudo apt-get install -y luajit

          # Compiler les scripts Lua dans le dossier "client"
          find client -name "*.lua" ! -name "config.lua" -exec luajit -b {} {}.luac \;

          # Compiler les scripts Lua dans le dossier "server" sauf svconfig.lua
          find server -name "*.lua" ! -name "svconfig.lua" -exec luajit -b {} {}.luac \;

          # Compiler les scripts Lua dans le dossier "shared" sauf config.lua
          find shared -name "*.lua" ! -name "config.lua" -exec luajit -b {} {}.luac \;

          # Renommer les fichiers compil√©s
          find . -name "*.luac" -exec rename 's/\.lua\.luac$/\.luac/' {} \;

      - name: Create ZIP file
        run: |
          find . -name "*.luac" -exec zip compiled_scripts.zip {} +

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Compiled Lua scripts
          draft: false
          prerelease: false

      - name: Upload ZIP file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: compiled_scripts.zip
          asset_name: compiled_scripts.zip
          asset_content_type: application/zip
